### ISSUE TITLE
how can I set to show header/footer display on post with category?

### ISSUE THREAD

**Issue by icq4ever** [brainstormforce/header-footer-elementor#343]
I cannot find post with category option. so if I want to do that, need to add every post title in "Specific Pages/ Posts / Taxonomies, etc." option.

### Additional context/screenshots

![image](https://user-images.githubusercontent.com/530796/106378439-2b014c80-63e8-11eb-9f5d-25684a39cb0f.png)

**Comment by pratikshasaman** [comment]
Hello @icq4ever,

Apologies for the delay in response!

We show categories directly instead of specific post with the category.

As of now, a specific post with a category option is not available.

I hope this helps.

Let us know if we can help with anything else.

Have a great day ahead!

Regards,
Pratiksha Samane

**Comment by pratikshasaman** [comment]
Hello @icq4ever,

We are closing this query as we did not hear back from you. Please do not hesitate to get back to us if you have any queries.
