### ISSUE TITLE
how to remove wp embed footer Bug Title ...

### ISSUE THREAD

**Issue by hirenm108** [brainstormforce/header-footer-elementor#539]
i have shared other product link in Product page 
as i have installed you plugin to set footer in my website 
but footer is showing in embed link also how to disable them

Link : https://designerkloth.com/product/haldi-yellow-lehenga/

SS : 
![image](https://user-images.githubusercontent.com/106644779/171326349-b7e9bbe1-026d-4b8f-a43f-1a558c51d363.png)

please let me know

**Comment by hirenm108** [comment]
This is setting used for footer

![image](https://user-images.githubusercontent.com/106644779/171326522-baa3ce5b-1bf2-442e-964f-b3722d275319.png)

**Comment by swapnilde** [comment]
Hello @hirenm108 

I think these hooks can help you with it:

```
remove_action( 'embed_footer', 'print_embed_scripts' );
remove_action( 'embed_footer', 'wp_print_footer_scripts' );
```

**Comment by vijetaR** [comment]
Hi @hirenm108 As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
