### ISSUE TITLE
Elementor Header & Footer Builder plugin causing margin's problems

### ISSUE THREAD

**Issue by zitacampos** [brainstormforce/header-footer-elementor#547]
Hello, 

I had to disable your plugin in order to have margins on our website, with your plugin active the website used to show like this - https://paste.pics/965bbd56d9b48ff0dceaa01c5b71d499 so I had to disable it. But that means I am no longer able to edit any of the header or footers. What is your suggestion to resolve this issue?

Thank you so much in advance

**Comment by swapnilde** [comment]
Hello @zitacampos 

Thank you for getting in touch with us.

Could you share the URL of your website with us where we can see the issue happening?
You can share some steps on how we can reproduce this on our end.
It is difficult to suggest anything without looking into it, making it easier to understand,
debug, and resolve an issue ASAP.

We are looking forward to hearing from you.

**Comment by vijetaR** [comment]
Hi @zitacampos Since we haven't received any further updates or responses regarding this specific issue, we will be marking this thread as "resolved" due to inactivity. Please be aware that you are more than welcome to initiate a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
