### ISSUE TITLE
I coudn't add specific page for my page exclusion rule, 

### ISSUE THREAD

**Issue by FloretoCulanag** [brainstormforce/header-footer-elementor#560]
[###](https://drive.google.com/file/d/1jfgQkRliScqtd5IhkpmxIjkb3QEKPbHv/view?usp=sharing) Describe the bug:

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [ ] I can reproduce this bug consistently using the steps above

**Comment by kinGxcaLi** [comment]
Has there been a fix found for this? Having the same issues. Looking to switch the footer for certain pages

**Comment by vijetaR** [comment]
Hi @FloretoCulanag, I have [checked](https://prnt.sc/nUxQ24hdX7S6) the condition at our end, the specific pages are getting loaded. As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
