### ISSUE TITLE
Elementor Widget Panel "loading" endlessly because of "Header Footer Elementor"

### ISSUE THREAD

**Issue by smochen** [brainstormforce/header-footer-elementor#561]
Elementor Widget Panel "loading" endlessly, when we deactivate your Plug-IN everything works fine.
If I make Elementor Rollback to 3.5.6 everything works as it should:

Screenshot:

https://my.elementor.com/wp-content/uploads/sites/2/gravity_forms/22-8fa82d82d4bd295a437b035bfb146a16/2022/03/Elementor11.jpg

**Comment by vijetaR** [comment]
Hi @smochen As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
