### ISSUE TITLE
404error after elementor updates

### ISSUE THREAD

**Issue by adriana0984** [brainstormforce/header-footer-elementor#581]
### Isolating the problem:

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

**Comment by vijetaR** [comment]
hi @adriana0984  As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
