### ISSUE TITLE
jquery sticky throwing errors

### ISSUE THREAD

**Issue by dthenley** [brainstormforce/header-footer-elementor#582]
### Describe the bug:
After updating elementor pro to the latest version 3.7.5, header and footer plugin is throwing the errror `Uncaught TypeError: this.$element.sticky is not a function` which is causing all of my other js animations to break as well.

### To reproduce:
Update elementor pro.
Have both elementor pro and header and footer plugin activated.

### Screenshots:
![image](https://user-images.githubusercontent.com/3503886/188334248-f1721a60-52b0-479b-bfed-cb92c2a19b8e.png)

### Isolating the problem:
I have deactivated all other plugins and is using stock Hello Elementor theme

- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.0.2

### Elementor version:
Elementor: 3.7.4
Elementor Pro: 3.7.5

**Comment by vijetaR** [comment]
Hi @dthenley As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
