### ISSUE TITLE
header hover not visible

### ISSUE THREAD

**Issue by Prernagera24** [brainstormforce/header-footer-elementor#586]
### Describe the bug: 
My header hover is not visible.
There are sub-heads in my header which are not visible.

### To reproduce:
Steps to reproduce the behavior

1. Go to stopperslifestyle.com
2. hover on 'shoes' in the header menu
3. See error

### Expected behavior:
The sub-heads should be visible on hovering on shoes.
he sub-heads are "men shoes" and "women shoes"

### WordPress version:
WordPress 6.0.2

### Elementor version:
Elementor v3.7.6

**Comment by vijetaR** [comment]
Hi @Prernagera24 As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Also, the site is not accessible to check. Hopefully the new updates has resolved the issue on the site. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
