### ISSUE TITLE
Navigation Menu dropdown does not collapse after activating another dropdown

### ISSUE THREAD

**Issue by IgorMiha71** [brainstormforce/header-footer-elementor#597]
When I activate one dropdown menu in Navigation Menu it opens, but then when I activate onother dropdown the first one stay open so I have to dropdowns open. 

Theme is oceanwp (no problem within it)
Everything updated to the latest versions.

Additional question> is it possible that drop down is opening on mouse over, not on click.
Thanks in advance.

**Comment by vijetaR** [comment]
Hi @IgorMiha71 To better understand and resolve the issue, we kindly request, if you could open a [support ticket ](https://brainstormforce.com/open-a-ticket/)with us and provide access to your demo site along with the necessary credentials, we would be more than happy to investigate the matter further. As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
