### ISSUE TITLE
The Plugin doesn't work always get Error when I want to use

### ISSUE THREAD

**Issue by FloretoCulanag** [brainstormforce/header-footer-elementor#603]
Hello, Please help me because I want to edit my header and footer using this awesome plugin that I have but the problem now is I cannot use the plugin anymore because of the error I always got when I want to edit my header and footer these header and footer are made from this plugin before since a started customizing my website. But now I always got an error. Thank you please help me solve this issue.
![header footer Builder error](https://user-images.githubusercontent.com/110441580/199024980-85142276-fdf0-4ccf-8466-f13b05af2ff7.JPG)

**Comment by vijetaR** [comment]
Hi @FloretoCulanag As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Hopefully no issue occurring with the latest updates, Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
