### ISSUE TITLE
font awesome / unicode encoding issues

### ISSUE THREAD

**Issue by cybersholt** [brainstormforce/header-footer-elementor#634]
### Describe the bug:
I'm working on this website, using Header, Footer & Blocks plugin. I started to notice intermittently that the HFE menu would display strange characters instead of the correct Font Awesome symbol. 

### To reproduce:
[View this sandbox](https://priceless-kate-s1d7t0.csb.app/)
[View this WP Demo](https://wp.cybersholt.com/)

### Related issues with similar behavior:
https://github.com/sass/dart-sass/issues/1219
https://github.com/OrchardCMS/OrchardCore/pull/10857

### Expected behavior:
The glyph should render correctly instead of displaying strange characters.

### Screenshots:
Correct Render:
![https://imgur.com/TRo4son](https://i.imgur.com/TRo4son.jpg)
Encoding Error Render:
![https://imgur.com/rK670C2](https://i.imgur.com/rK670C2.jpg)

### Isolating the problem:
- [x] This bug happens with no other plugins activated
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:
6.1.1

### Elementor version:
3.9.2

### Elementor - Header, Footer & Blocks version:
1.6.13

#### Notes
It can be quite difficult to reproduce, I was able fix it a few months ago by replacing the glyphs with the unicode and adding 
```@charset "utf-8";``` 
to the head of the file.  

I'll create a PR for this asap.

**Comment by vijetaR** [comment]
Hi @cybersholt No issue is [occurring](https://prnt.sc/KmJjOmcoWruY) at our end with the latest update. As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
