### ISSUE TITLE
Footer not sticking

### ISSUE THREAD

**Issue by boliseneku** [brainstormforce/header-footer-elementor#642]
I am using the twenty-twenty theme and Elementor header and footer. The footer is only sticky on the front (home) page and not at the bottom of other pages. I have tried using CSS to put the footer at the bottom and to remain there, no joy. It then overlapped when using CSS at fixed position, not even the Calc worked. What adjustment do I need to do? Now at the end of my tether after searching the web and ChatGPT.

**Comment by vijetaR** [comment]
Hi @boliseneku, To better understand and resolve the issue, we kindly request, if you could open a support ticket with us and provide access to your demo site along with the necessary credentials, we would be more than happy to investigate the matter further.  As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.

**Comment by boliseneku** [comment]
What year was this issue raised?
