### ISSUE TITLE
Page refresh after click on anchor link

### ISSUE THREAD

**Issue by mvldebian** [brainstormforce/header-footer-elementor#660]
When clicking on a anchor link in the menu that was generated by the plugin
The page goes to where the content is, but when reaching the specified point, the page reloads

To reproduce the error access https://transbus.srv.br
Click on Home and after on any of the links in the submenu

Thank you in advance
Wordpress 6.1.1
Elementor 3.11.2
Theme LandingPress 2.0.1

**Comment by vijetaR** [comment]
Hi @mvldebian, I visited the link you provided and noticed that the page didn't refresh when I visited it. Since we haven't received any more updates or responses about this issue, we will consider this matter resolved due to inactivity. Please feel free to start a new conversation if you need more help or have questions about our plugin or any other topic.
