### ISSUE TITLE
Wordpress 6.2 version, Elementor 3.11.5 version, your plugin has not been updated for a long time to be compatibleBug Title ...

### ISSUE THREAD

**Issue by HaiwangTT** [brainstormforce/header-footer-elementor#662]
Wordpress 6.2 version, Elementor 3.11.5 version, your plugin has not been updated for a long time to be compatibleBug Title ...

**Comment by vijetaR** [comment]
Hi @HaiwangTT Our plugin is updated to the latest version of WordPress and Elementor. As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
