### ISSUE TITLE
"Elementor Header & Footer Builder" Header isn't working with the Elementor PRO Header

### ISSUE THREAD

**Issue by aminul-xs** [brainstormforce/header-footer-elementor#739]
1. Install the "**Elementor Header & Footer Builder**" plugin and go to "WP Admin > Appearance > Elementor Header & Footer Builder.
2. Go to "**Elementor Header & Footer Builder** > Header Footer", create a Header template,
3. Try to edit an Elementor Header template and verify the Can't Edit problem, make sure  **Elementor PRO** Installed

**Comment by azertyuiop896** [comment]
Same issue

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue you encountered in the Elementor Header & Footer Builder plugin has been addressed in the latest update, version 1.6.19. Kindly install this update to resolve the problem. Thank you for your understanding, and please let us know if you encounter any further issues after updating.

**Comment by aminul-xs** [comment]
[It is not fixed](https://prnt.sc/PEIXfQNyx0b6)

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue in the Elementor Header & Footer Builder plugin has been fixed in the latest update (version 1.6.20). Please install this update to resolve the issue. Let us know if you face any more issues after updating. Thank you!

**Comment by vijetaR** [comment]
Hello @aminul-xs, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
