### ISSUE TITLE
Last update to 1.6.18 broke my Header and Footer due to incorrect rendering of SVG image

### ISSUE THREAD

**Issue by Dret42** [brainstormforce/header-footer-elementor#742]
I'm using **Elementor Free 3.18** whith **Elementor Header & Footer Builder 1.16.7** and all works fine.

But today I made the update from1.16.17 to 1.6.18 version. 

As result my Header and Footer (that contain Logo and other resources in SVG format) **now does not render SVG anymore** and broke my site. 

I made a rollback to the previous version (1.16.17) and all works fine again.

Please control the compatibility of new version of plugin when Header or Footer embeed SVG resorces (via file or inline).

Thanks in advance.
Bye

PS. I found also that new version broke the "search icon/form" Widget

**Comment by vijetaR** [comment]
Apologies for the trouble. The issue you encountered in the Elementor Header & Footer Builder plugin has been addressed in the latest update, version 1.6.19. Kindly install this update to resolve the problem. Thank you for your understanding, and please let us know if you encounter any further issues after updating.

**Comment by Dret42** [comment]
Thanks, now all works well!

**Comment by vijetaR** [comment]
Hi @Dret42, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
