### ISSUE TITLE
Footer links not working

### ISSUE THREAD

**Issue by khotchkiss92** [brainstormforce/header-footer-elementor#773]
I created a footer with the Header & Footer Elementor Builder, with 3 sections.

1. Call
2. Email
3. Location

All 3 text links go to a 404 page, and when I add the mailto: or tel: html link to the email address and telephone number, it doesn't work. It just writes the link text in the footer, no link.

Also, I want to unlink the location text as well, but don't have that access.

Is anyone else having this issue or can help me?

Thanks!

![footer](https://github.com/brainstormforce/header-footer-elementor/assets/160911442/cf3f318f-04e7-4edd-ae6f-d71f20c04aab)

**Comment by vijetaR** [comment]
Hello @khotchkiss92,
Thank you for reporting the issue with the footer links. We’re sorry for the inconvenience. The issue is not reproducible on our end. Screencast for reference [Here](https://bsf.d.pr/v/z2BEIw)

Please try the following steps to resolve the issue:
- Edit Links: In the Header & Footer Elementor Builder, update the Email and Call links accordingly. Remove the link from the Location text and save the changes.
- Clear Cache: Clear your browser and site cache.
- Verify: Refresh your site and check if the links are working correctly.
- Ensure you are using the latest version of the Header & Footer Elementor Builder and Elementor. 

If the issue still persists, please open a [support ticket](https://brainstormforce.com/open-a-ticket/) and provide access to your staging site for further investigation.

**Comment by vijetaR** [comment]
Hello @khotchkiss92 , As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin or any other matter.
