### ISSUE TITLE
Nav Menu animation

### ISSUE THREAD

**Issue by aymen3009** [brainstormforce/header-footer-elementor#797]
I would like to have some open animation in my navigation menu but I couldn't find where to find

**Comment by vijetaR** [comment]
Hi @aymen3009, We provide submenu animations for the navigation menu. Could you check if that's what you're looking to add to your navigation menu? Please let us know if this resolves your query or if you need further assistance.
https://prnt.sc/Dvgr_pJ556DU

**Comment by vijetaR** [comment]
Hello @aymen3009,

As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "Resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin, or any other matter.
