### ISSUE TITLE
Schema markup created by elementor header and footer builder

### ISSUE THREAD

**Issue by fiXmarketing** [brainstormforce/header-footer-elementor#853]
### Describe the bug:
Ehf Menu creates a "WPHeader" schema markup, that can´t be removed.

**Comment by vijetaR** [comment]
Hello @fiXmarketing ,

You can remove the "WPHeader" schema markup by adding a filter to your theme’s `functions.php` file. 

Here’s how:

1. Open your WordPress Admin Dashboard.
2. Navigate to Appearance > Theme File Editor.
3. Find and click on the `functions.php` file.
4. Add the following code at the end of the file:

```php
// Disable HFE Header Rendering
add_filter( 'enable_hfe_render_header', '__return_false' );
```

5. Click "Update File" to save your changes.

This will remove the rendering of the header with the `WPHeader` schema markup. After completing these steps, please let us know if the issue is resolved. Your feedback is important to us and helps us improve the experience for all users.

**Comment by vijetaR** [comment]
Hi @fiXmarketing, Since we haven't received any more updates or responses about this issue, we will consider this matter resolved due to inactivity. Please feel free to start a new conversation if you need more help or have questions about our plugin or any other topic
