### ISSUE TITLE
Cannot edit with elementor header and footer builder

### ISSUE THREAD

**Issue by plastictom9** [brainstormforce/header-footer-elementor#854]
### Describe the bug:
I cannot edit with the elementor header and footer builder (befor 4 days it still worked)

I start elementor header and footer builder and then the screen stucks with the elementor logo
Its the same as lkeuuuuu mentioned May 24th, but I have the version 1.6.37
I tried to deactivate the plugin and afterwards activate it again, but the bug was already there.

### WordPress version:
Version 6.5.5 and the OceanWP-Theme v3.5.8

### Elementor version:
3.23.1

**Comment by vijetaR** [comment]
Hello @plastictom9 

Hi, If you encounter issues with the Elementor – Header Footer & Block Template plugins, such as loading problems or editing difficulties, try the following steps:
1) [Flush](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/) the Permalinks
2) Deactivate and Reactivate the plugin and see if that helps.
3) Switch to a default theme and check if the issue persists, to switch back to your current theme.
4) Roll back the plugin to an older version and then upgrade to the latest version (if the above steps don’t help). You can roll back using a plugin like [WP Rollback](https://wordpress.org/plugins/wp-rollback/).

If you have low memory due to plugins, increase the WordPress memory limit to at least 256M or up to 512M by editing the wp-config.php file. Also, deactivate unused widgets from Elementor Addons plugins to reduce server requests and memory usage. Let us know how it goes.

**Comment by plastictom9** [comment]
Hello to all of you,

thanks for your mail! It works! Point 3. was the solution for my case.

Thanks a lot
Best regards
 Thomas
________________________________
Von: Vijeta Raikar ***@***.***>
Gesendet: Donnerstag, 18. Juli 2024 09:47
An: brainstormforce/header-footer-elementor ***@***.***>
Cc: plastictom9 ***@***.***>; Mention ***@***.***>
Betreff: Re: [brainstormforce/header-footer-elementor] Cannot edit with elementor header and footer builder (Issue #854)


Hello @plastictom9<https://github.com/plastictom9>

If you encounter issues with the Elementor – Header Footer & Block Template plugins, such as loading problems or editing difficulties, try the following steps:

  1.  Flush<https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/> the Permalinks
  2.  Deactivate and Reactivate the plugin and see if that helps.
  3.  Switch to a default theme and check if the issue persists, to switch back to your current theme.
  4.  Roll back the plugin to an older version and then upgrade to the latest version (if the above steps don’t help). You can roll back using a plugin like WP Rollback<https://wordpress.org/plugins/wp-rollback/>.

If you have low memory due to plugins, increase the WordPress memory limit to at least 256M or up to 512M by editing the wp-config.php file. Also, deactivate unused widgets from Elementor Addons plugins to reduce server requests and memory usage. Let us know how it goes.

**Comment by vijetaR** [comment]
Hello @plastictom9, Since the issue has been successfully resolved, we're closing this GitHub thread. Please feel free to start a new conversation if you need more help or have questions about our plugin or any other topic. Thank you!
