### ISSUE TITLE
White Blank Screen on home Page (White Screen of Death)

### ISSUE THREAD

**Issue by DomCan123** [brainstormforce/header-footer-elementor#885]
Dear Support,

Ive had issues with going into the theme that we have for Elementor Futurio. Everytime i go to the home page it shows a white screen. Ive been getting this error on site ground server im using. Any help to fix this issue id appreciate.

2024-09-16 06:12:39 UTC [apache][authz_core:error] [pid 39518] [client 44.240.37.43:12136] AH01630: client denied by server configuration: /home/customer/www/mrdavesmidis.com/public_html/wp-content/themes/futurio/index.php

Many thanks,
Dominic

**Comment by sushmak02** [comment]
Hello @DomCan123 ,

Thank you for reaching out. The error you're seeing, "client denied by server configuration," is likely related to server settings rather than the theme.

Here are a few things you can try:

- Ensure that the index.php file in your Futurio theme has the correct permissions (usually 644 for files and 755 for directories).
- Review your .htaccess file for any custom rules that might block access.
- Contact SiteGround support to check if any server configurations, like mod_security, are causing the issue.

Let us know if this helps or if you need further assistance.

**Comment by DomCan123** [comment]
Hi Sushmak02,
I have looked at the files it Futuro and they have file permissions 644, and ive reviewed all .htaccess and cant see any errors here. Ill check with Siteground server that i use and see if they have a solution there.

Many thanks,
Dominic

**Comment by vijetaR** [comment]
Here, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin.
