### ISSUE TITLE
Cannot Edit Header and Footer with Elementor

### ISSUE THREAD

**Issue by grayhawkdjc** [brainstormforce/header-footer-elementor#919]
### Describe the bug:

I am not able to edit my header and footer with Elementor.

### Expected behavior:

To be able to edit the header and footer.

### Screenshots:

![image](https://github.com/user-attachments/assets/3ecabe40-69fa-471d-8392-d10e2794b7e1)
![image](https://github.com/user-attachments/assets/cf5f9112-0369-4a60-a714-b3cf5e3736a2)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently using the steps above

### WordPress version:

WordPress 6.6.2
### Elementor version:

Elementor - 3.24.7

**Comment by vijetaR** [comment]
Hello,

Thanks for reporting the issue. We’re currently investigating it but haven’t been able to replicate it on our end.

Some users have resolved the issue by following these steps. Please try the steps below and check if the issue is resolved.

- Flush WordPress [Permalinks](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/).
- Deactivate and reactivate the HFE plugin.
- Switch to a default WordPress theme, then switch back to your current theme.

If the problem persists for you, please open a [support ticket](https://brainstormforce.com/open-a-ticket/) here so we can gather more information and troubleshoot further. Your input will help us resolve this as quickly as possible.

**Comment by gabriele-carbonai** [comment]
I also have the same problem and the console shows me the same errors. I solved it by simply flushing the permalinks

**Comment by grayhawkdjc** [comment]
Thanks Vijeta and Gabriele. I did try this as well by flushing the
permalinks and it worked. Appreciate your help with this.

Hien

**Comment by sngm** [comment]
Flushing the permalinks works for me too. Ty @vijetaR

**Comment by vijetaR** [comment]
Here, As we haven't received any further updates or responses regarding this particular issue, we will be marking this thread as "resolved" due to inactivity. Please know that you are more than welcome to start a new thread if you require any additional assistance or have further questions related to our plugin.
