### ISSUE TITLE
Erro no carregamento

### ISSUE THREAD

**Issue by KempesSign** [brainstormforce/header-footer-elementor#964]
Após a última atualização não consigo abrir mais os arquivos de header e footer para editar, o elementor fica carregando e não conclui, isso está acontecendo em alguns sites que gerencio. 

Wordpress = Versão 6.7.1
Elementor = Versão 3.25.10
Elementor Header & Footer Builder = Versão 1.6.47

![image](https://github.com/user-attachments/assets/683a08d0-5dc4-4a55-8071-ce44553959e5)

Alguem tem uma solução?

**Comment by vijetaR** [comment]
Hello @KempesSign,

Thanks for reporting the issue. We’re currently investigating it but haven’t been able to replicate it on our end.

Some users have resolved the issue by following these steps. Please try the steps below and check if the issue is resolved.

- Flush WordPress [Permalinks](https://wpastra.com/docs/how-to-refresh-wordpress-permalinks/).
- Deactivate and reactivate the plugin.
- Switch to a default WordPress theme, then switch back to your current theme.
- Update to latest version of the plugin. 

If the problem persists for you, please open a [support ticket](https://brainstormforce.com/open-a-ticket/) here so we can gather more information and troubleshoot further. Your input will help us resolve this as quickly as possible.
